### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by divan** [tidwall/shiny#1]
Hey, thanks for the cool project. The name is conflicting with Go experimental UI lib, though.
https://github.com/golang/exp/tree/master/shiny

I think in Go community name "shiny" is already strongly linked to this lib.

Opening this issue just to raise the concern as early as possible, because changing the name is easier at the early stage of project.

**Comment by tidwall** [comment]
Thanks for bringing this to my attention.  The exp/shiny project looks pretty neat. Do you know what the future plans are for the project’s name? From the surface I can’t tell if it’s something that’s intended to be a standard Go package or not.

**Comment by divan** [comment]
No idea. I think `exp/shiny` targets mobile platforms in some feature. Unlikely to be in stdlib.

**Comment by tidwall** [comment]
FYI. I just changed the name to avoid conflict. :)
