### ISSUE TITLE
About the Reactor pattern

### ISSUE THREAD

**Issue by Luncher** [tidwall/shiny#4]
hi Josh
Can you explain where the Reactor pattern is used in this project? I understand that the Reactor pattern and the Proactor pattern are implemented by the kernel, not the things that the application layer needs to worry about. Maybe I don't understand. I'm looking forward to your explanation.

**Comment by tidwall** [comment]
Hi Lin,

Yikes. It's very possible that my definition of Reactor is not correct. I always thought that the reactor pattern just means that multiple inputs are demultiplexed into a single event based output. Shiny simply adheres to the existing reactor pattern that comes with kqueue and epoll.

**Comment by Luncher** [comment]
I've learned a lot by studying your code. In addition to epoll and kqueue, I also want to add select support. How did you like it?

**Comment by Luncher** [comment]
PS：What kind of work do you do now? If there is a proper open source project, you can share it with me, and I'd love to.

**Comment by tidwall** [comment]
> I've learned a lot by studying your code. In addition to epoll and kqueue, I also want to add select support. How did you like it?

I think adding select would be fine, but right now Shiny falls back to using the standard net library.

> PS：What kind of work do you do now? If there is a proper open source project, you can share it with me, and I'd love to.

Most of my time is working on updates to Tile38 and a bunch of C code. Mostly updates to existing projects that I have on my Github page. Nothing super new atm.
